
  backend:
  name: github
  repo: votre-nom-utilisateur/nom-du-depot # Remplacez par votre chemin GitHub
  branch: main # ou master
  base_url: https://votre-site.vercel.app # L'URL de votre site une fois déployé
  auth_endpoint: api/auth


media_folder: "images/uploads" # dossier où seront stockées les images
public_folder: "/images/uploads"

collections:
  - name: "posts" # utilisé pour les routes
    label: "Articles" # nom dans l'interface
    folder: "posts" # dossier où seront stockés les fichiers markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image à la une", name: "image", widget: "image", required: false }
      - { label: "Extrait", name: "excerpt", widget: "text", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }
