backend:
  name: github
  repo: Claudia-py/aprn # Remplacez par votre vrai nom de dépôt
  branch: main
  base_url: https://github-os-auth.vercel.app
  


media_folder: "Images" # dossier où seront stockées les images
public_folder: "/Images"

collections:
  - name: "Posts" # utilisé pour les routes
    label: "Articles" # nom dans l'interface
    folder: "Posts" # dossier où seront stockés les fichiers markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image à la une", name: "image", widget: "image", required: false }
      - { label: "Extrait", name: "excerpt", widget: "text", required: false }
      - { label: "Contenu", name: "body", widget: "markdow 
